### PR TITLE
Execute bash commands

### PR DESCRIPTION
**Pull request by margaretjoanmiller**

### CODE REVIEW

**Comment by CreaturePhil** [comment]
Why are you changing license? Everything else looks good and thanks for fixing my mistakes!

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Creative Commons is kind of "meh", I can change it back if you want.

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Thanks!

**Comment by CreaturePhil** [comment]
Nah the change in license is fine.

**Pull request merged**
